load("5.R.RData")
head(Xy)
pairs(Xy)
plot(y~X1, data = Xy)
plot(y~X2, data = Xy)
corrgram::corrgram(Xy)
fit = lm(formula = y ~ X1 + X2, data = Xy)
summary(fit)
matplot(Xy,type="l", col = c("red","green", "blue"))
summary(Xy$X1)
hist(Xy$X1)